### ISSUE TITLE
Error on launch after installing plugin 

### ISSUE THREAD

**Issue by webpablo** [GvnCampbell/homebridge-powerview#2]
`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 54565478-0a52-41f9-a781-00f6fbe1305e
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-powerview-master/index.js:89:13
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
`

**Comment by GvnCampbell** [comment]
I've seen this before with other plugins.  For some reason homebridge would get confused and the only way I would be able to get it working properly was to totally reset and start from scratch.  I don't think its an issue with this specific plugin.
